# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a77d928118672e96458f9030dfcb98bd0d6422f0e6e3be700ded87aa457fc606460ed2fac1fa7a020bc693cfb637b5421f0f762956d1a515d1aaddaf54b9108

test:
  secret_key_base: 99a864c9f2b7aead949ccae655e7462edd95cf8546838c63467d57614b0071f6535040b294ec9420c7a92030d8861fa3b21f0a814a110f9b1bb4b57dc36856a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
